name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
      - run: |
          sed -i 's/gradle-.*-all.zip/gradle-8.0-all.zip/' android/gradle/wrapper/gradle-wrapper.properties
          find $HOME/.pub-cache -path "*print_bluetooth_thermal*" -name "pubspec.yaml" -exec sed -i '/windows:/d' {} \; || true
          flutter config --no-enable-windows --no-enable-macos --no-enable-linux --no-enable-web
          echo "org.gradle.jvmargs=-Xmx4G" >> android/gradle.properties
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: APK-JADI
          path: build/app/outputs/flutter-apk/app-release.apk
