name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
      - name: fix
        run: |
          flutter config --no-enable-windows-desktop --no-enable-macos-desktop --no-enable-linux-desktop --no-enable-web
          flutter pub get
          find $HOME/.pub-cache -path *print_bluetooth_thermal*/pubspec.yaml -exec sed -i /windows:/d {} \;
          sed -i -E s/1.7.10/1.9.22/g android/settings.gradle
          sed -i -E s/1.8.22/1.9.22/g android/settings.gradle
          sed -i s/compileSdkVersion.*/compileSdkVersion\ 34/ android/app/build.gradle
          sed -i s/targetSdkVersion.*/targetSdkVersion\ 34/ android/app/build.gradle
      - run: flutter build apk --release --no-tree-shake-icons
      - uses: actions/upload-artifact@v4
        with:
          name: DR-Aquatic-APK
          path: build/app/outputs/flutter-apk/app-release.apk
